### ISSUE TITLE
Use custom env var names

### ISSUE THREAD

**Issue by codan84** [Bardavon-Health/actions-aws-ssm-params-to-env#88]
Say I'd like to read SSM on path `/my-service/db/url`, but I do not want just a `$url` env var, I want `$DB_URL`. Config could look like:
```
- uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.3.2
  with:
    ssm-path: /my-service/db/url
    var-name: DB_URL
```
Saves me doing it manually after this action...

**Comment by dennybiasiolli** [comment]
Have you tried to use it like this?

```yml
- uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.3.2
  with:
    ssm-path: /my-service/db
    prefix: DB_
```
